# Generated by Django 5.0.4 on 2024-08-20 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('admin_delete', 'Deleted by Admin'), ('upload_failed', 'Upload Failed')], max_length=32)),
                ('hash_corpus_path', models.CharField(max_length=32)),
                ('real_corpus_path', models.CharField(max_length=100)),
                ('corpus_first_entry', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corpus',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('index_status', models.CharField(choices=[('queued', 'Queued'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('screening', 'Screening'), ('paused', 'Paused'), ('finished', 'Finished'), ('archived', 'Archived'), ('indexing_error', 'Indexing Error')], max_length=32)),
                ('current_screening_page', models.IntegerField(default=1, null=True)),
                ('p_query_path', models.JSONField(null=True)),
                ('i_query_path', models.JSONField(null=True)),
                ('c_query_path', models.JSONField(null=True)),
                ('o_query_path', models.JSONField(null=True)),
                ('ranking_pages', models.JSONField(null=True)),
                ('page_screening_log', models.JSONField(null=True)),
                ('include_docs', models.JSONField(null=True)),
                ('exclude_docs', models.JSONField(null=True)),
                ('maybe_docs', models.JSONField(null=True)),
                ('started_screening_at', models.DateTimeField(null=True)),
                ('paused_screening_at', models.DateTimeField(null=True)),
                ('finished_screening_at', models.DateTimeField(null=True)),
                ('pos_at_waiting_queue', models.IntegerField()),
                ('job_queued_at', models.DateTimeField()),
                ('job_started_at', models.DateTimeField(null=True)),
                ('job_ended_at', models.DateTimeField(null=True)),
                ('indexing_error_msg', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encoder.corpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
