# Generated by Django 4.2.16 on 2024-10-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='corpus4tevatron',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='docid2pmid',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='pmids',
            field=models.TextField(default=None, null=True),
        ),
    ]
