# Generated by Django 4.2.16 on 2024-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0002_corpus_corpus4tevatron_corpus_docid2pmid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('admin_delete', 'Deleted by Admin'), ('user_delete', 'Deleted by User'), ('upload_failed', 'Upload Failed')], max_length=32),
        ),
    ]
