# Generated by Django 4.2.16 on 2024-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0003_alter_corpus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='archived_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='c_query_path',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='exclude_docs',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='finished_screening_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='i_query_path',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='include_docs',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='indexing_error_msg',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_queued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='maybe_docs',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='o_query_path',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='p_query_path',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='page_screening_log',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='paused_screening_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ranking_pages',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='started_screening_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
