# Generated by Django 4.2.16 on 2024-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0004_alter_review_archived_at_alter_review_c_query_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='corpus_first_entry',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='hash_corpus_path',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='real_corpus_path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
