# Generated by Django 4.2.16 on 2024-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0006_rename_c_query_path_review_pico_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='screening_status',
            field=models.CharField(choices=[('not_start', 'Not Start'), ('screening', 'Screening'), ('paused', 'Paused'), ('finished', 'Finished')], default='not_start', max_length=32),
        ),
    ]
