# Generated by Django 4.2.16 on 2024-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0007_review_screening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='pmids',
            field=models.JSONField(default=None, null=True),
        ),
    ]
