# Generated by Django 4.2.16 on 2024-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0008_alter_corpus_pmids'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_docs_per_page',
            field=models.IntegerField(default=25),
        ),
    ]
