# Generated by Django 4.2.16 on 2024-12-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0009_review_show_docs_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_interaction',
            field=models.JSONField(default=None, null=True),
        ),
    ]
