# Generated by Django 4.2.16 on 2024-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0010_review_user_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='index_status',
        ),
        migrations.AddField(
            model_name='review',
            name='index_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('indexing', 'Indexing'), ('index_ready', 'Indexing Ready'), ('re-ranking', 'Re-ranking'), ('re-ranking_ready', 'Re-ranking ready'), ('archived', 'Archived'), ('indexing_error', 'Indexing Error')], default='index_ready', max_length=32),
            preserve_default=False,
        ),
    ]
