export const config = {
  username: {
    dataKey: 'username',
    label: 'Username',
    type: 'text',
    download: false,
    downloadBtn: false,
    row: 1,
    mandatory: true,
    feedback: false,
  },
  password: {
    dataKey: 'password',
    label: 'Password',
    type: 'password',
    download: false,
    downloadBtn: false,
    row: 1,
    mandatory: true,
    feedback: true,
  },
  confirmPassword: {
    dataKey: 'confirm_password',
    label: 'Confirm Password',
    type: 'password',
    download: false,
    downloadBtn: false,
    row: 1,
    mandatory: true,
    feedback: false,
  },
  email: {
    dataKey: 'email',
    label: 'Email',
    type: 'text',
    download: false,
    downloadBtn: false,
    row: 1,
    mandatory: true,
    feedback: false,
  },
  confirmEmail: {
    dataKey: 'confirm_email',
    label: 'Confirm Email',
    type: 'text',
    download: false,
    downloadBtn: false,
    row: 1,
    mandatory: true,
    feedback: false,
  },
}
